### ISSUE TITLE
Installation OK but no config .toml to be found

### ISSUE THREAD

**Issue by GrayCygnus** [brocaar/chirpstack-packet-multiplexer#11]
I followed the steps as indicated, and reached the part of editing the .toml config file. However, it is nowhere to be found...

>To complete the installation, update the configuration file which is located at /etc/chirpstack-packet-multiplexer/chirpstack-packet-multiplexer.toml and (re)start the service:
>>sudo systemctl restart chirpstack-packet-multiplexer

Such folder under `/etc` does not exist, nor the .toml... I ran a search from root and no results of such .toml...
Running `chirpstack-packet-multiplexer configfile` does print the default configuration shown in the Readme...

Any hints on this one?
Running on Ubuntu 20.04. Another colleague tried in 18.04 and had the same issue.

Thanks

**Comment by ccall48** [comment]
```toml
[general]
# Log level
#
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=4

[packet_multiplexer]
# Bind
#
# The interface:port on which the packet-multiplexer will bind for receiving
# data from the packet-forwarder (UDP data).
bind="0.0.0.0:1800"

# Backends
#
# The backends to which the packet-multiplexer will forward the
# packet-forwarder UDP data.
#

# # First place to multiplex to... this is my chirpstack network server running in docker
[[packet_multiplexer.backend]]
# # ChirpStack Router & Gateway IDs
host="chirpstack-docker_chirpstack-gateway-bridge_1:1700"
# uplink_only=false
# #
# # The Gateway IDs to forward data for.
gateway_ids = [
  "<YOUR GW 1 EUI>",	# gateway 1 eui
  "<YOUR GW 2 EUI>",	# gateway 2 eui
  "<YOUR GW 3 EUI>",	# gateway 3 eui
  "<YOUR GW 4 EUI>",	# gateway 4 eui
]

# # Second place to multiplex to... Add as many of these blocks as you need
[[packet_multiplexer.backend]]
host="<HOST:PORT>"
# uplink_only=false
# #
# # The Gateway IDs to forward data for.
gateway_ids = [
  "<YOUR GW 1 EUI>",	# gateway 1 eui
  "<YOUR GW 2 EUI>",	# gateway 2 eui
  "<YOUR GW 3 EUI>",	# gateway 3 eui
  "<YOUR GW 4 EUI>",	# gateway 4 eui
]
```

Try this example, add or remove as many blocks as you need. Likewise with the gateways you need in each block.
